UI.WebMatricula3C2023/Controllers/EstudianteController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using UI.WebMatricula3C2023.Logica;

namespace UI.WebMatricula3C2023.Controllers
{
    public class EstudianteController : Controller
    {
        LnEstudiante lnEstudiante = new LnEstudiante();

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public async Task<IActionResult> Index()
        {
            Models.Estudiante.Entrada.VerTodosEstudiantes parametros = 
                new Models.Estudiante.Entrada.VerTodosEstudiantes();

            var usuarioActual = HttpContext.Session.GetObjectFromJson<Models.Users.User>("UsuarioActual");

            var listaEstudiantes = await lnEstudiante.VerTodosEstudiantes(parametros, usuarioActual.Token);

            ////////////////***********GRAFICOS CHART JS//////////////////////*********/
            var random = new Random();

            var etiquetas = new List<string>();
            var colores = new List<string>();
            var valores = new List<string>();

            foreach(var estado in listaEstudiantes.ListaEstudiantes.GroupBy(e => e.Estado)
                .Select(group => new { 
                    Estado = group.Key,
                    Cantidad = group.Count()
                }).OrderBy(x => x.Estado))
            {
                string color = String.Format("#{0:X6}", random.Next(0x1000000));

                etiquetas.Add(estado.Estado);
                valores.Add(estado.Cantidad.ToString());
                colores.Add(color);
            }

            ViewBag.Etiquetas = JsonConvert.SerializeObject(etiquetas);
            ViewBag.Valores = JsonConvert.SerializeObject(valores);
            ViewBag.Colores = JsonConvert.SerializeObject(colores);
            ////////////////***********GRAFICOS CHART JS//////////////////////*********/

            return View(listaEstudiantes.ListaEstudiantes);
        }

        [HttpPost]
        public async Task<JsonResult> AgregarEstudiante(Models.Estudiante.Entrada.AgregarEstudiante agregarEstudiante)
        {
            var usuarioActual = HttpContext.Session.GetObjectFromJson<Models.Users.User>("UsuarioActual");
            var codigo = await lnEstudiante.AgregarEstudiante(agregarEstudiante, usuarioActual.Token);

            if (codigo != null)
                return Json(String.Format("El estudiante: {0} ha sido ingresado con éxito.",agregarEstudiante.NombreCompleto));
            else
                return Json(String.Format("El estudiante: {0} no fue ingresado.", agregarEstudiante.NombreCompleto));
        }

        [HttpPost]
        public async Task<JsonResult> EditarEstudiante(Models.Estudiante.Entrada.EditarEstudiante editarEstudiante)
        {
            var usuarioActual = HttpContext.Session.GetObjectFromJson<Models.Users.User>("UsuarioActual");
            var codigo = await lnEstudiante.EditarEstudiante(editarEstudiante, usuarioActual.Token);

            if (codigo != null)
                return Json(String.Format("El estudiante: {0} ha sido modificado con éxito.", editarEstudiante.NombreCompleto));
            else
                return Json(String.Format("El estudiante: {0} no fue modificado.", editarEstudiante.NombreCompleto));
        }

        [HttpPost]
        public async Task<JsonResult> EliminarEstudiante(Models.Estudiante.Entrada.EliminarEstudiante eliminarEstudiante)
        {
            var usuarioActual = HttpContext.Session.GetObjectFromJson<Models.Users.User>("UsuarioActual");
            var codigo = await lnEstudiante.EliminarEstudiante(eliminarEstudiante, usuarioActual.Token);

            if (codigo != null)
                return Json(String.Format("El estudiante: {0} ha sido eliminado con éxito.", eliminarEstudiante.Codigo));
            else
                return Json(String.Format("El estudiante: {0} no fue eliminado.", eliminarEstudiante.Codigo));
        }

        [HttpPost]
        public async Task<JsonResult> VerDetalleEstudiante(Models.Estudiante.Entrada.VerDetalleEstudiante verDetalleEstudiante)
        {
            var usuarioActual = HttpContext.Session.GetObjectFromJson<Models.Users.User>("UsuarioActual");
            var respuesta = await lnEstudiante.VerDetalleEstudiante(verDetalleEstudiante, usuarioActual.Token);
            
            return Json(respuesta);
        }


    }
}

UI.WebMatricula3C2023/Controllers/PerfilController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using UI.WebMatricula3C2023.Logica;

namespace UI.WebMatricula3C2023.Controllers
{
    public class PerfilController : Controller
    {
        [Authorize]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Index()
        {
            var usuarioActual = HttpContext.Session.GetObjectFromJson<Models.Users.User>("UsuarioActual");
            return View(usuarioActual);
        }

    }
}

UI.WebMatricula3C2023/Views/Shared/_ExternalLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UI.WebMatricula3C2023</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UI.WebMatricula3C2023.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

UI.WebMatricula3C2023/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UI.WebMatricula1C2023</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UI.WebMatricula3C2023.styles.css" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/2.2.3/css/buttons.dataTables.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/2.2.3/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.colVis.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.html5.min.js"></script>

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }
    </style>
</head>
<body>
    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow gradient-custom-2" style="background-color: #eee;">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" asp-controller="Home" asp-action="Index">Punto de venta</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        @* <input class="form-control form-control-dark" type="text" placeholder="Buscar" aria-label="Search">*@
        <div class="navbar-nav">
            <div class="nav-item text-nowrap">
                <a class="nav-link px-3" asp-controller="Acceso" asp-action="Logout">Cerrar sesión</a>
            </div>
        </div>
    </header>

    <div class="container-fluid">
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="position-sticky pt-3">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">
                                <span data-feather="home"></span>
                                Dashboard
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file"></span>
                                Cursos
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-controller="CategoriaProducto" asp-action="Index">
                                <span data-feather="grid"></span>
                                Profesores
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Producto" asp-action="Index">
                                <span data-feather="shopping-cart"></span>
                                Matrícula
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Estudiante" asp-action="Index">
                                <span data-feather="users"></span>
                                Estudiantes
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="bar-chart-2"></span>
                                Reportes
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Perfil" asp-action="Index">
                                <span data-feather="user"></span>
                                Mi perfil
                            </a>
                        </li>
                    </ul>

                    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>Otros</span>
                        <a class="link-secondary" href="#" aria-label="Add a new report">
                            <span data-feather="plus-circle"></span>
                        </a>
                    </h6>
                    <ul class="nav flex-column mb-2">
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Falcon Pride
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Fiesta de fin de año
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>

            @RenderBody()

        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - UI.WebMatricula1C2023 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/Producto.js"></script>
    <script src="~/js/Estudiante.js"></script>
    <script src="~/js/dashboard.js" asp-append-version="true"></script>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>